ALTER TABLE users
  ADD COLUMN IF NOT EXISTS department VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE menus
  ADD COLUMN IF NOT EXISTS category VARCHAR(80) NOT NULL DEFAULT 'lunch',
  ADD COLUMN IF NOT EXISTS cutoff_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS max_orders INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE orders
  DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE orders
  ADD CONSTRAINT orders_status_check CHECK (status IN ('placed', 'confirmed', 'delivered', 'cancelled'));
